name: Go package

on: [push]

jobs:
   build-macos:
      name: Build(macos-latest)
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go1.19.2
          uses: actions/setup-go@v3
          with:
            go-version: 1.19
        - name: Display Go version
          run: go version
        # 使用 https://username:密钥@github.com 替换 https://github.com 可避免github登录
        - name: Get dependencies
          run: |
                go get -v -t -d ./...                
        - name: Download dependency
          run: go mod tidy
        - name: Go Build(ubuntu)
          run: go build -v ./...
 
        - name : upload execution
          uses: actions/upload-artifact@master
          if: always()
          with:
            # zip压缩包的名称为 action1.1.zip(使用的go module 默认名称)
            # (若干多个build时，此名称相同，则合并打包到一个zip中)
            name: action-macos-amd
            # 将 action打包到 action1.1.zip中并把 action1.1.zip 上传到github的本次action的Artifacts下
            path: ${{ github.workspace }}/goaction 
        
 